#!/bin/bash
application_dir="/home/pi/.nu/"
application_name="nud"

wallet01_unit="B"
wallet01_ramdisk="walletB.dat.ramdisk"
wallet01_ramdisk_bak="walletB.dat.ramdisk.bak"
wallet01_ramdisk_bak2="walletB.dat.ramdisk.bak2"

wallet02_unit="S"
wallet02_ramdisk="walletS.dat.ramdisk"
wallet02_ramdisk_bak="walletS.dat.ramdisk.bak"
wallet02_ramdisk_bak2="walletS.dat.ramdisk.bak2"

if [ -f $application_dir$wallet01_ramdisk_bak ]; then
        mv $application_dir$wallet01_ramdisk_bak $application_dir$wallet01_ramdisk_bak2
fi

if [ -f $application_dir$wallet02_ramdisk_bak ]; then
        mv $application_dir$wallet02_ramdisk_bak $application_dir$wallet02_ramdisk_bak2
fi

echo "writing $application_dir$wallet01_ramdisk"
echo $application_name -unit=$wallet01_unit backupwallet $application_dir$wallet01_ramdisk_bak
$application_name -unit=$wallet01_unit backupwallet $application_dir$wallet01_ramdisk_bak

echo "writing $application_dir$wallet02_ramdisk"
echo $application_name -unit=$wallet02_unit backupwallet $application_dir$wallet02_ramdisk_bak
$application_name -unit=$wallet02_unit backupwallet $application_dir$wallet02_ramdisk_bak

sleep 1
$application_name stop
